INSERT INTO systemuser (email, name, password, registerdate, surname, type, username) VALUES ('admin@oleoguide.com', 'Administrator', 'admin', current_date, 'Administrator', 'Admin', 'admin');

INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (1, 1);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (1, 2);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (2, 5);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (2, 10);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (3, 10);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (4, 1);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (4, 2);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (5, 3);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (7, 2);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (8, 10);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (8, 5);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (9, 10);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (10, 5);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (8, 8);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (12, 7);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (12, 9);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (12, 6);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (13, 4);
INSERT INTO restaurant_foodtype (foodtypes_id, restaurants_id) VALUES (14, 12);